### ISSUE TITLE
Please provide an example of how to use it...

### ISSUE THREAD

**Issue by Poikilos** [BenjamenMeyer/rsync4python#2]
...otherwise I don't know why I should choose it. I can't dig through the code of every one of the many rsync search results on PyPi, some of which are wrappers or reimplementations and only one of which that I can see ([rsyncwrap](https://pypi.org/project/rsyncwrap/)) implements a callback. Add an example both in the readme and at PyPI please.

**Comment by BenjamenMeyer** [comment]
@poikilos I've added PR #3 for two things:
- Address the issue here of adding an example
- Updating librsync

When I last worked on this with Python 3.4 it seemed to have issues due to a lacking of the Python API to be able to do what I wanted to do. At least running it as-is right now this seemed to work - my old tests passed. That said, it may still need work to get it working under Python3; I've done a minimal effort to make the tests work again while doing that PR.

Hope it helps and hope you find a good solution.

FYI - A pure python implementation is rather slow. I was doing this for a Rsync-As-A-Service on top of Rackspace Cloud Files years back where this was the Rsync implementation; I think I was only using Python2 at the time though (I no longer have access to that code). Any how - good luck, and PRs are welcome. I'll try to address anything, but you'll likely be able to debug faster.
